parameters:
  alpha: 1.0e-05
  batch_size: 1024
  best_validation_test: true
  buckets: 3
  clustering: kmeans
  create_outputfile: true
  cw_pcba: 1000.0
  data: pcba
  gamma: 1.0
  id: config_pcba_shared_lbtw
  lambda: ''
  maml_split_prop: 0.8
  max_epochs: 50
  model: Standard
  num_experts: 20
  num_units: 20
  output: config_pcba_shared_lbtw
  prob_exclusivity: 0.75
  prop: 1.0
  hidden_size: 2000
  runits:
  - 2000
  save_tensor: false
  task_balance_method: DWA
  tasks:
  - ''
  type_exc: exclusion
